#!/usr/bin/env python3
"""
Fine-tune phoneme embeddings for ChatterBox T3.

Strategy:
    1. FREEZE all original model weights (520M params)
    2. Train ONLY the new phoneme embedding rows (~75 × 1024 = ~77K params)
       and optionally unfreeze text_head for the new rows
    3. Training data: phonemized text from MLS/CommonVoice paired with
       speech tokens from the frozen S3 tokenizer

This is extremely lightweight — runs on a single L4 GPU in minutes.

Usage:
    python scripts/finetune_phoneme_embeddings.py \
        --ckpt-dir /path/to/weights \
        --data-dir /path/to/mls/data \
        --lang it \
        --epochs 5 \
        --device cuda:1
"""

import argparse
import json
import logging
import os
import sys
import time
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# Add project root
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


class PhonemeTextDataset(Dataset):
    """Dataset of (phoneme_token_ids, speech_tokens) pairs.

    Each sample is pre-tokenized and stored as tensors.
    Generated by the prepare_data() step below.
    """

    def __init__(self, data_path: str):
        self.data = torch.load(data_path, weights_only=True)
        logger.info(f"Loaded {len(self.data)} samples from {data_path}")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]


def collate_fn(batch):
    """Pad text and speech tokens to batch max length."""
    text_tokens = [item["text_tokens"] for item in batch]
    speech_tokens = [item["speech_tokens"] for item in batch]
    text_lens = torch.tensor([len(t) for t in text_tokens])
    speech_lens = torch.tensor([len(s) for s in speech_tokens])

    max_text = text_lens.max().item()
    max_speech = speech_lens.max().item()

    # Pad with stop token (0)
    text_padded = torch.zeros(len(batch), max_text, dtype=torch.long)
    speech_padded = torch.zeros(len(batch), max_speech, dtype=torch.long)

    for i, (t, s) in enumerate(zip(text_tokens, speech_tokens)):
        text_padded[i, :len(t)] = t
        speech_padded[i, :len(s)] = s

    return {
        "text_tokens": text_padded,
        "text_token_lens": text_lens,
        "speech_tokens": speech_padded,
        "speech_token_lens": speech_lens,
    }


def prepare_training_data(
    ckpt_dir: str,
    audio_dir: str,
    transcript_file: str,
    lang: str,
    output_path: str,
    max_samples: int = 5000,
    device: str = "cuda:1",
):
    """Prepare training data: phonemize text + tokenize speech.

    Args:
        ckpt_dir: path to model weights
        audio_dir: directory containing wav files
        transcript_file: TSV file with columns: audio_path, transcript
        lang: language code
        output_path: where to save the prepared data
        max_samples: max number of samples
        device: CUDA device
    """
    from chatterbox.models.t3.modules.t3_config import T3Config
    from chatterbox.models.tokenizers import MTLTokenizer
    from chatterbox.models.s3tokenizer import S3_SR
    from chatterbox.phoneme_tokens import text_to_phonemes, phonemes_to_token_ids, get_all_new_tokens

    import librosa

    ckpt_dir = Path(ckpt_dir)

    # Load tokenizer in phoneme mode
    tokenizer = MTLTokenizer(
        str(ckpt_dir / "grapheme_mtl_merged_expanded_v1.json"),
        phoneme_mode=True,
    )

    # Load S3 tokenizer for speech tokens
    from chatterbox.models.s3tokenizer import S3Tokenizer
    s3_tokenizer = S3Tokenizer()
    s3_tokenizer.to(device).eval()

    # Read transcripts
    samples = []
    with open(transcript_file) as f:
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) >= 2:
                audio_path, text = parts[0], parts[1]
                # Make path absolute if relative
                if not os.path.isabs(audio_path):
                    audio_path = os.path.join(audio_dir, audio_path)
                samples.append((audio_path, text))

    if max_samples:
        samples = samples[:max_samples]

    logger.info(f"Processing {len(samples)} samples for [{lang}]...")

    config = T3Config.multilingual_phoneme()
    sot = config.start_text_token
    eot = config.stop_text_token

    prepared = []
    skipped = 0

    for i, (audio_path, text) in enumerate(samples):
        if i % 100 == 0:
            logger.info(f"  [{i}/{len(samples)}] processed ({skipped} skipped)")

        try:
            # 1. Phonemize text → token IDs
            text_ids = tokenizer.encode(text, language_id=lang)
            if not text_ids:
                skipped += 1
                continue

            # Add SOT/EOT
            text_ids = [sot] + text_ids + [eot]
            text_tokens = torch.tensor(text_ids, dtype=torch.long)

            # 2. Load audio → speech tokens
            wav, sr = librosa.load(audio_path, sr=S3_SR)
            if len(wav) < S3_SR * 0.5:  # skip < 0.5s
                skipped += 1
                continue

            with torch.inference_mode():
                speech_tokens, _ = s3_tokenizer.forward(
                    [wav], max_len=config.max_speech_tokens
                )
                speech_tokens = speech_tokens.squeeze(0).cpu()

            # Add start/stop speech tokens
            start_speech = torch.tensor([config.start_speech_token], dtype=torch.long)
            stop_speech = torch.tensor([config.stop_speech_token], dtype=torch.long)
            speech_tokens = torch.cat([start_speech, speech_tokens, stop_speech])

            prepared.append({
                "text_tokens": text_tokens,
                "speech_tokens": speech_tokens,
            })

        except Exception as e:
            logger.warning(f"Error processing {audio_path}: {e}")
            skipped += 1
            continue

    logger.info(f"Prepared {len(prepared)} samples ({skipped} skipped)")

    torch.save(prepared, output_path)
    logger.info(f"Saved to {output_path}")
    return output_path


def train(
    ckpt_dir: str,
    data_path: str,
    lang: str,
    epochs: int = 5,
    batch_size: int = 4,
    lr: float = 1e-3,
    device: str = "cuda:1",
    save_every: int = 1,
    output_dir: str = None,
):
    """Fine-tune phoneme embeddings.

    Only trains:
    - text_emb.weight rows [2454:] (phoneme embeddings)
    - text_head.weight rows [2454:] (phoneme head)

    Everything else is frozen.
    """
    from safetensors.torch import load_file as load_safetensors, save_file as save_safetensors
    from chatterbox.models.t3 import T3
    from chatterbox.models.t3.modules.t3_config import T3Config, BPE_VOCAB_SIZE
    from chatterbox.models.t3.modules.cond_enc import T3Cond
    from chatterbox.mtl_tts import _extend_t3_state_with_phonemes

    ckpt_dir = Path(ckpt_dir)
    output_dir = Path(output_dir) if output_dir else ckpt_dir

    # --- Load model ---
    logger.info("Loading T3 with phoneme config...")
    config = T3Config.multilingual_phoneme()
    t3 = T3(config)

    # Load and extend checkpoint
    t3_path = ckpt_dir / "t3_phoneme.safetensors"
    if not t3_path.exists():
        t3_path = ckpt_dir / "t3_mtl23ls_v2.safetensors"
        logger.info(f"Loading base checkpoint: {t3_path}")
        state = load_safetensors(str(t3_path))
        if "model" in state:
            state = state["model"][0]
        state = _extend_t3_state_with_phonemes(state, config.text_tokens_dict_size)
    else:
        logger.info(f"Loading extended checkpoint: {t3_path}")
        state = load_safetensors(str(t3_path))

    t3.load_state_dict(state, strict=True)
    t3.to(device)

    # --- Freeze everything except phoneme rows ---
    for name, param in t3.named_parameters():
        param.requires_grad = False

    # Unfreeze text_emb and text_head (we'll mask gradients to only update new rows)
    t3.text_emb.weight.requires_grad = True
    t3.text_head.weight.requires_grad = True

    n_total = sum(p.numel() for p in t3.parameters())
    n_train = sum(p.numel() for p in t3.parameters() if p.requires_grad)
    logger.info(f"Parameters: {n_total:,} total, {n_train:,} trainable "
                f"({100*n_train/n_total:.2f}%)")

    # --- Hook to zero out gradients for original BPE rows ---
    def mask_bpe_gradients(grad):
        """Zero out gradients for the original BPE token rows (0:2454)."""
        grad[:BPE_VOCAB_SIZE] = 0
        return grad

    t3.text_emb.weight.register_hook(mask_bpe_gradients)
    t3.text_head.weight.register_hook(mask_bpe_gradients)

    # --- Dataset ---
    dataset = PhonemeTextDataset(data_path)
    dataloader = DataLoader(
        dataset, batch_size=batch_size, shuffle=True,
        collate_fn=collate_fn, num_workers=2, pin_memory=True,
    )

    # --- Optimizer (only new rows, but we optimize full params + mask grads) ---
    optimizer = torch.optim.AdamW(
        [t3.text_emb.weight, t3.text_head.weight],
        lr=lr, weight_decay=0.01,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs * len(dataloader),
    )

    # --- We need conditioning for training. Use a dummy/default one. ---
    # Load default conditionals from the checkpoint
    conds_path = ckpt_dir / "conds.pt"
    if conds_path.exists():
        from chatterbox.mtl_tts import Conditionals
        conds = Conditionals.load(conds_path).to(device)
        t3_cond = conds.t3
    else:
        logger.warning("No conds.pt found — using zero conditioning (not ideal)")
        dim = config.n_channels
        t3_cond = T3Cond(
            speaker_emb=torch.zeros(1, 256, device=device),
            cond_prompt_speech_tokens=torch.ones(1, 150, dtype=torch.long, device=device) * 6561,
            emotion_adv=0.5 * torch.ones(1, 1, 1, device=device),
        )

    # --- Training loop ---
    logger.info(f"Starting training: {epochs} epochs, {len(dataloader)} batches/epoch")
    t3.train()

    # But keep everything except emb/head in eval mode
    t3.tfmr.eval()
    t3.cond_enc.eval()
    t3.speech_emb.eval()

    for epoch in range(epochs):
        epoch_loss_text = 0.0
        epoch_loss_speech = 0.0
        epoch_steps = 0
        t0 = time.time()

        for batch in dataloader:
            text_tokens = batch["text_tokens"].to(device)
            text_lens = batch["text_token_lens"].to(device)
            speech_tokens = batch["speech_tokens"].to(device)
            speech_lens = batch["speech_token_lens"].to(device)

            # Expand conditioning for batch
            B = text_tokens.size(0)
            batch_cond = T3Cond(
                speaker_emb=t3_cond.speaker_emb.expand(B, -1),
                cond_prompt_speech_tokens=t3_cond.cond_prompt_speech_tokens.expand(B, -1),
                emotion_adv=t3_cond.emotion_adv.expand(B, -1, -1),
            )

            loss_text, loss_speech = t3.loss(
                t3_cond=batch_cond,
                text_tokens=text_tokens,
                text_token_lens=text_lens,
                speech_tokens=speech_tokens,
                speech_token_lens=speech_lens,
            )

            loss = loss_text + loss_speech
            optimizer.zero_grad()
            loss.backward()
            # Gradient masking is handled by the hook
            optimizer.step()
            scheduler.step()

            epoch_loss_text += loss_text.item()
            epoch_loss_speech += loss_speech.item()
            epoch_steps += 1

        dt = time.time() - t0
        avg_text = epoch_loss_text / max(epoch_steps, 1)
        avg_speech = epoch_loss_speech / max(epoch_steps, 1)
        lr_now = scheduler.get_last_lr()[0]
        logger.info(
            f"Epoch {epoch+1}/{epochs} | "
            f"loss_text={avg_text:.4f} loss_speech={avg_speech:.4f} | "
            f"lr={lr_now:.2e} | {dt:.1f}s"
        )

        # Save checkpoint
        if (epoch + 1) % save_every == 0 or epoch == epochs - 1:
            save_path = output_dir / f"t3_phoneme_ep{epoch+1}.safetensors"
            save_state = {k: v.cpu() for k, v in t3.state_dict().items()}
            save_safetensors(save_state, str(save_path))
            logger.info(f"Saved: {save_path}")

    # Save final as t3_phoneme.safetensors
    final_path = output_dir / "t3_phoneme.safetensors"
    final_state = {k: v.cpu() for k, v in t3.state_dict().items()}
    save_safetensors(final_state, str(final_path))
    logger.info(f"Final checkpoint: {final_path}")

    # Verify original weights not modified
    orig_state = load_safetensors(str(ckpt_dir / "t3_mtl23ls_v2.safetensors"))
    orig_emb = orig_state["text_emb.weight"]
    new_emb = final_state["text_emb.weight"][:BPE_VOCAB_SIZE]
    if torch.allclose(orig_emb, new_emb, atol=1e-6):
        logger.info("VERIFIED: Original BPE embeddings unchanged")
    else:
        max_diff = (orig_emb - new_emb).abs().max().item()
        logger.warning(f"WARNING: BPE embeddings changed! Max diff: {max_diff}")


def main():
    parser = argparse.ArgumentParser(description="Fine-tune phoneme embeddings")
    subparsers = parser.add_subparsers(dest="command")

    # Prepare data
    prep = subparsers.add_parser("prepare", help="Prepare training data")
    prep.add_argument("--ckpt-dir", required=True)
    prep.add_argument("--audio-dir", required=True)
    prep.add_argument("--transcripts", required=True, help="TSV: audio_path\\ttranscript")
    prep.add_argument("--lang", required=True)
    prep.add_argument("--output", required=True)
    prep.add_argument("--max-samples", type=int, default=5000)
    prep.add_argument("--device", default="cuda:1")

    # Train
    tr = subparsers.add_parser("train", help="Fine-tune embeddings")
    tr.add_argument("--ckpt-dir", required=True)
    tr.add_argument("--data", required=True, help="Prepared data .pt file")
    tr.add_argument("--lang", required=True)
    tr.add_argument("--epochs", type=int, default=5)
    tr.add_argument("--batch-size", type=int, default=4)
    tr.add_argument("--lr", type=float, default=1e-3)
    tr.add_argument("--device", default="cuda:1")
    tr.add_argument("--output-dir", default=None)

    args = parser.parse_args()

    if args.command == "prepare":
        prepare_training_data(
            ckpt_dir=args.ckpt_dir,
            audio_dir=args.audio_dir,
            transcript_file=args.transcripts,
            lang=args.lang,
            output_path=args.output,
            max_samples=args.max_samples,
            device=args.device,
        )
    elif args.command == "train":
        train(
            ckpt_dir=args.ckpt_dir,
            data_path=args.data,
            lang=args.lang,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            device=args.device,
            output_dir=args.output_dir,
        )
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
